export const DEFAULT_IS_DEBUGGER_MINIMIZED = false
export const DEFAULT_SHOW_DEBUGGER = true
export const DEFAULT_SHOW_NAME_TAGS = true
export const DEFAULT_SORT_ELEMENT_LIST = "visibility" as const
export const MAX_POSITION_HISTORY_SIZE = 30
export const MAX_SCROLL_MARGIN = 300
export const MAX_TAB_OFFSET = 20
export const MAX_TRAJECTORY_PREDICTION_TIME = 200
export const MIN_POSITION_HISTORY_SIZE = 2
export const MIN_SCROLL_MARGIN = 30
export const MIN_TAB_OFFSET = 0
export const MIN_TRAJECTORY_PREDICTION_TIME = 10
export const POSITION_HISTORY_SIZE_UNIT = "points"
export const SCROLL_MARGIN_UNIT = "px"
export const TAB_OFFSET_UNIT = "tabs"
export const TRAJECTORY_PREDICTION_TIME_UNIT = "ms"
