export { ForesightManager } from "./managers/ForesightManager"
export type { HasListenersFunction } from "./core/BaseForesightModule"
export type {
  Rect as ForesightRect,
  ForesightElement,
  ForesightElementState,
  ForesightRegisterResult,
  UpdateForsightManagerSettings,
  ForesightManagerSettings,
  ForesightCallback,
  ForesightRegisterOptions,
  ForesightRegisterNodeListOptions,
  ForesightRegisterOptionsWithoutElement,
  ForesightEvent,
  ForesightEventMap,
  ElementRegisteredEvent,
  DeviceStrategyChangedEvent,
  ElementReactivatedEvent,
  ElementUnregisteredEvent,
  ElementDataUpdatedEvent,
  CallbackInvokedEvent,
  CallbackCompletedEvent,
  MouseTrajectoryUpdateEvent,
  ScrollTrajectoryUpdateEvent,
  ManagerSettingsChangedEvent,
  UpdatedManagerSetting,
  HitSlop,
  CallbackHitType,
  CallbackHits,
  TouchDeviceStrategy,
  MinimumConnectionType,
  Point as ForesightPoint,
  ScrollDirection,
  ForesightManagerData,
  UpdatedDataPropertyNames,
} from "./types/types"
