export { ForesightManager } from "./manager/ForesightManager"
export type {
  Rect as ForesightRect,
  ForesightElement,
  ForesightRegisterResult,
  UpdateForsightManagerSettings,
  ForesightManagerSettings,
  ForesightRegisterOptions,
  ForesightRegisterOptionsWithoutElement,
  ForesightElementData,
  CallbackHits as ForesightCallbackHits,
  ForesightEvent,
  ElementRegisteredEvent,
  ElementUnregisteredEvent,
  ElementDataUpdatedEvent,
  CallbackInvokedEvent,
  CallbackCompletedEvent,
  MouseTrajectoryUpdateEvent,
  ScrollTrajectoryUpdateEvent,
  ManagerSettingsChangedEvent,
  HitSlop,
  CallbackHitType,
} from "./types/types"
